# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Andy Lavedrine
email: andy.lavedrine@orange.fr
description: Candidat Monde Académie - Entrepreneur (bientôt!) - Etudiant à l'Ecole d'Economie de Paris
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Social media profiles - feel free to add more here
linkedin_username: andylavedrine
github_username:  lavedrina
facebook_username: andy.lavedrine

# Address information
address_street: 105 rue Didot
address_city: Paris
address_zip: 75014

# Build settings
markdown: kramdown
